version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  redis:
    networks:
      - my-network
    image: "abtestingplayground.azurecr.io/redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-commander:
    networks:
      - my-network
    image: "abtestingplayground.azurecr.io/rediscommander/redis-commander:latest"
    container_name: "my-redis-commander-container"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  api:
    networks:
      - my-network
    image: "abtestingplayground.azurecr.io/playground-api:latest"
    container_name: "my-api-container"
    ports:
      - "5103:80"
    depends_on:
      - redis

  client:
    networks:
      - my-network
    image: "abtestingplayground.azurecr.io/playground-client:latest"
    container_name: "my-client-container"
    ports:
      - "4200:80"
    depends_on:
      - api
