version: '3.8'

networks:
  playground-network:
    driver: bridge

services:  
  app:
    networks:
      - playground-network
    image: "abtesting.azurecr.io/playground:latest"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        progress: plain
    container_name: "playground"
    ports:
      - "5103:80"

volumes:
  redis-data:
