# The name of the deployment
name: Build & deploy to Azure Container App

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    # Branched to look out for changes on
    branches:
      - main
      - feature/*
    paths:
      - playground/**
      - '!playground/README.md'

  # Allow manually trigger of the jobs
  workflow_dispatch:

jobs:
  # Job run image.
  build:
    runs-on: ubuntu-latest

    # Steps that need to happen in this job run.
    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Log in to Azure CLI
      - name: Log in to Azure
        uses: azure/login@v2.1.1
        with:
          # Azure CLI credentials
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build and deploy the container app
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/playground
          acrName: abtesting
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: abtesting-playground
          containerAppEnvironment: abtesting-app-env
          resourceGroup: rg-abtesting
          imageToBuild: abtesting.azurecr.io/playground:${{ github.sha }}
          dockerfilePath: Dockerfile
          environmentVariables:
            ANALYTICS_CLARITY_ID=${{ secrets.ANALYTICS_CLARITY_ID }}
            ANALYTICS_GA_MEASUREMENT_ID=${{ secrets.ANALYTICS_GA_MEASUREMENT_ID }}
            ConnectionStrings__AppConfig=secretref:app-config-cs
            APPINSIGHTS_INSTRUMENTATIONKEY=secretref:insights-instrumentation-key
            ApplicationInsights__InstrumentationKey=secretref:insights-instrumentation-key
            WEBSITES_PORT=80
            ConnectionStrings__AppInsights=secretref:insights-cs
          buildArguments:
            ANALYTICS_CLARITY_ID=${{ secrets.ANALYTICS_CLARITY_ID }}
            ANALYTICS_GA_MEASUREMENT_ID=${{ secrets.ANALYTICS_GA_MEASUREMENT_ID }}