name: Publish to NPM
on:
  release:
    types: [published]

  push:
    branches:
      - feature/*
    paths:
      - packages/abtesting/**
      - .github/workflows/npm.yml

  # Allow manually trigger of the jobs
  workflow_dispatch:
    inputs:
      dispatch-type:
        type: choice
        description: Release type
        options:
          - Preview
          - Release

env:
  WORKING_DIRECTORY: packages/abtesting

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci
      - name: Publish package on NPM 📦
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
