name: Publish NPM
on:
  release:
    types: [published]

  push:    
    branches:
      - feature/*
    paths:
      - packages/Nuget/IPSAG.AbTesting/**
      - .github/workflows/nuget.yml
    
  # Allow manually trigger of the jobs
  workflow_dispatch:  
    inputs:
      dispatch-type:
        type: choice
        description: Release type
        options: 
        - Preview
        - Release
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
