name: Publish to Nuget

on:
  release:
    types: [published]
  push:    
    branches:
      - feature/*
    paths:
      - packages/Nuget/IPSAG.AbTesting/**
      - .github/workflows/nuget.yml
    
  # Allow manually trigger of the jobs
  workflow_dispatch:  
    inputs:
      dispatch-type:
        type: choice
        description: Release type
        options: 
        - Preview
        - Release

env:
  projectName: IPSAG.AbTesting
  projectPath: ${{ github.workspace }}/packages/Nuget/IPSAG.AbTesting
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NUGET_VERSION: '1.0.0'
  
jobs:
  build:
    env:
        BUILD_CONFIG: 'Release'
        SHARED_ARGS: '-p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }}/packages/Nuget/IPSAG.AbTesting -p:RepositoryType=git'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
      - name: Set Build Number Environment Variable
        run: |
          echo "BUILD_NUMBER=${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV
          echo $BUILD_NUMBER
      - name: Build & Pack Preview
        if: ${{ github.event.inputs.dispatch-type != 'Release'}}
        run: dotnet build ${{ env.projectPath }}/${{ env.projectName }}.csproj --configuration $BUILD_CONFIG -p:Version=${{ env.NUGET_VERSION }}-preview$BUILD_NUMBER ${{ env.SHARED_ARGS}}

      - name: Build & Pack Release
        if: ${{ github.event.inputs.dispatch-type == 'Release'}}
        run: dotnet build ${{ env.projectPath }}/${{ env.projectName }}.csproj --configuration $BUILD_CONFIG -p:Version=${{ env.NUGET_VERSION }} ${{ env.SHARED_ARGS}}

      - name: Push
        run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY  }}
