name: Publish Nuget Pre-release

on:
  push:
    branches:
      - feature/*
    paths:
      - playground/Nuget/**
    
  # Allow manually trigger of the jobs
  workflow_dispatch:

env:
  projectName: Ips.AbTesting
  projectPath: ${{ github.workspace }}/playground/Nuget/Ips.AbTesting
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
      - name: Get Build Version
        run: |
          Import-Module .\modules\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
      - name: Build
        run: dotnet build ${{ env.projectPath }}/${{ env.projectName }}.csproj --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore
        
      - name: Push ${{ env.projectName }}.$BUILD_VERSION.nupkg
        run: dotnet nuget push ${{ env.projectName }}.$BUILD_VERSION.nupkg --source https://nuget.pkg.github.com/ips-ag/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
